(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(column-number-mode t)
 '(company-idle-delay 0.01)
 '(compilation-message-face 'default)
 '(custom-enabled-themes '(zenburn))
 '(custom-safe-themes
   '("06f0b439b62164c6f8f84fdda32b62fb50b6d00e8b01c2208e55543a6337433a" "f2c35f8562f6a1e5b3f4c543d5ff8f24100fae1da29aeb1864bbc17758f52b70" "816bacf37139d6204b761fea0d25f7f2f43b94affa14aa4598bce46157c160c2" "f3ab34b145c3b2a0f3a570ddff8fabb92dafc7679ac19444c31058ac305275e1" "a37d20710ab581792b7c9f8a075fcbb775d4ffa6c8bce9137c84951b1b453016" "76c5b2592c62f6b48923c00f97f74bcb7ddb741618283bdb2be35f3c0e1030e3" "a7051d761a713aaf5b893c90eaba27463c791cd75d7257d3a8e66b0c8c346e77" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" "a2cde79e4cc8dc9a03e7d9a42fabf8928720d420034b66aecc5b665bbf05d4e9" default))
 '(gc-cons-threshold 100000000)
 '(helm-completion-style 'emacs)
 '(highlight-changes-colors '("#FD5FF0" "#AE81FF"))
 '(highlight-indent-guides-method 'bitmap)
 '(highlight-indent-guides-responsive 'stack)
 '(highlight-tail-colors
   '(("#3C3D37" . 0)
     ("#679A01" . 20)
     ("#4BBEAE" . 30)
     ("#1DB4D0" . 50)
     ("#9A8F21" . 60)
     ("#A75B00" . 70)
     ("#F309DF" . 85)
     ("#3C3D37" . 100)))
 '(initial-frame-alist '((fullscreen . maximized)))
 '(large-file-warning-threshold 100000000)
 '(lsp-file-watch-threshold 10000)
 '(lsp-headerline-breadcrumb-enable nil)
 '(lsp-lens-debounce-interval 0.001)
 '(lsp-lens-enable nil)
 '(lsp-lens-place-position 'end-of-line)
 '(lsp-prefer-flymake nil)
 '(lsp-rust-analyzer-cargo-watch-args [])
 '(lsp-rust-analyzer-display-chaining-hints nil)
 '(lsp-rust-analyzer-display-parameter-hints nil)
 '(lsp-rust-analyzer-server-command '("rust-analyzer-wrapper"))
 '(lsp-rust-server 'rust-analyzer)
 '(lsp-rust-target-dir "lsp")
 '(lsp-signature-auto-activate nil)
 '(lsp-signature-function 'eldoc-message)
 '(lsp-signature-render-documentation nil)
 '(lsp-ui-doc-delay 0.1)
 '(lsp-ui-doc-max-height 15)
 '(lsp-ui-doc-max-width 60)
 '(lsp-ui-doc-position 'top)
 '(lsp-ui-doc-show-with-cursor t)
 '(lsp-ui-doc-show-with-mouse nil)
 '(lsp-ui-flycheck-enable t)
 '(lsp-ui-sideline-delay 0.01)
 '(lsp-ui-sideline-enable t)
 '(lsp-ui-sideline-show-code-actions t)
 '(lsp-ui-sideline-show-hover t)
 '(lsp-ui-sideline-wait-for-all-symbols nil)
 '(magit-diff-use-overlays nil)
 '(package-selected-packages
   '(adwaita-dark-theme k8s-mode lua-mode bind-key f ht hydra json-reformat lsp-treemacs macrostep magit-section pcache pfuture polymode posframe s treemacs helm-lsp use-package dap-mode graphviz-dot-mode gitlab-ci-mode systemd multiple-cursors sql-indent sqlup-mode transpose-frame csv-mode color-theme-sanityinc-tomorrow buffer-move async haskell-mode json-snatcher pythonic reformatter ansible ansible-doc ansible-vault poly-ansible highlight-indent-guides jenkinsfile-mode scala-mode sqlformat protobuf-mode counsel swiper ivy avy dash dash-functional git-commit helm-core lsp-mode lv markdown-mode popup transient typescript-mode with-editor hc-zenburn-theme dockerfile-mode rich-minority 0blayout jinja2-mode po-mode cython-mode cmake-mode pkgbuild-mode auto-yasnippet helm-c-yasnippet yasnippet-classic-snippets yasnippet-snippets yasnippet monokai-theme framemove projectile-speedbar window-purpose sr-speedbar yaml-mode web-mode tide scss-mode geiser flycheck-rust cargo rust-mode company-anaconda anaconda-mode lsp-ui company-lsp json-mode js2-mode rainbow-mode elisp-slime-nav slime rainbow-delimiters key-chord company helm-ag helm-descbinds helm-projectile helm exec-path-from-shell zop-to-char zenburn-theme which-key volatile-highlights undo-tree super-save smartrep smartparens operate-on-number move-text magit projectile imenu-anywhere hl-todo guru-mode gitignore-mode gitconfig-mode git-timemachine gist flycheck expand-region epl editorconfig easy-kill diminish diff-hl discover-my-major crux browse-kill-ring beacon anzu ace-window))
 '(pos-tip-background-color "#FFFACE")
 '(pos-tip-foreground-color "#272822")
 '(prelude-whitespace nil)
 '(rich-minority-mode t)
 '(rm-blacklist nil)
 '(safe-local-variable-values
   '((eval ansible-doc-mode t)
     (eval poly-ansible-mode t)
     (eval poly-ansible)
     (eval ansible-doc)
     (eval ansible)))
 '(size-indication-mode t)
 '(sqlformat-command 'pgformatter)
 '(tool-bar-mode nil)
 '(warning-suppress-log-types '((comp)))
 '(weechat-color-list
   '(unspecified "#272822" "#3C3D37" "#F70057" "#F92672" "#86C30D" "#A6E22E" "#BEB244" "#E6DB74" "#40CAE4" "#66D9EF" "#FB35EA" "#FD5FF0" "#74DBCD" "#A1EFE4" "#F8F8F2" "#F8F8F0"))
 '(yas-prompt-functions
   '(yas-x-prompt yas-dropdown-prompt yas-completing-prompt yas-maybe-ido-prompt yas-no-prompt)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :slant normal :weight normal :height 120 :width normal))))
 '(easy-kill-selection ((t (:inverse-video t))))
 '(flycheck-error ((t (:underline "#BC8383"))))
 '(flycheck-warning ((t (:underline "#F0DFAF"))))
 '(highlight ((t (:background "dim gray"))))
 '(region ((t (:distant-foreground "black" :inverse-video t))))
 '(rust-builtin-formatting-macro ((t (:inherit font-lock-preprocessor-face))))
 '(rust-question-mark ((t (:inherit font-lock-type-face :weight bold))))
 '(rust-unsafe ((t (:inherit font-lock-warning-face :foreground "coral")))))

